/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author Peniche
 */
public class AdministracionDatos extends javax.swing.JFrame {

    /**
     * Creates new form RegistraEmpleado
     */
    public AdministracionDatos() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Administración de datos.");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        botonRegistroEmpleado = new javax.swing.JButton();
        botonBorrarEmpleado = new javax.swing.JButton();
        botonModificar = new javax.swing.JButton();
        botonVolver = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        agregarProducto = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(922, 520));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 3, 30)); // NOI18N
        jLabel1.setText("Menú");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(730, 50, 180, 50);

        botonRegistroEmpleado.setFont(new java.awt.Font("Monotype Corsiva", 0, 28)); // NOI18N
        botonRegistroEmpleado.setText("Registrar Empleado");
        botonRegistroEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRegistroEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(botonRegistroEmpleado);
        botonRegistroEmpleado.setBounds(10, 160, 260, 40);

        botonBorrarEmpleado.setFont(new java.awt.Font("Monotype Corsiva", 0, 28)); // NOI18N
        botonBorrarEmpleado.setText("Borrar Empleado");
        botonBorrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarEmpleadoActionPerformed(evt);
            }
        });
        getContentPane().add(botonBorrarEmpleado);
        botonBorrarEmpleado.setBounds(10, 110, 260, 40);

        botonModificar.setFont(new java.awt.Font("Monotype Corsiva", 0, 28)); // NOI18N
        botonModificar.setText("Modificar Información");
        botonModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonModificarActionPerformed(evt);
            }
        });
        getContentPane().add(botonModificar);
        botonModificar.setBounds(10, 210, 270, 40);

        botonVolver.setFont(new java.awt.Font("Monotype Corsiva", 0, 28)); // NOI18N
        botonVolver.setText("Atrás");
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(botonVolver);
        botonVolver.setBounds(2, 2, 100, 40);

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 3, 30)); // NOI18N
        jLabel3.setText("Administración de Datos");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 40, 330, 70);

        agregarProducto.setFont(new java.awt.Font("Monotype Corsiva", 0, 28)); // NOI18N
        agregarProducto.setText("Agregar bebida/plato");
        agregarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarProductoActionPerformed(evt);
            }
        });
        getContentPane().add(agregarProducto);
        agregarProducto.setBounds(660, 110, 250, 40);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Desktop\\Sistema de restaurant\\SistemaRestaurant\\src\\Images\\fondo1.jpg")); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 920, 498);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonModificarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botonModificarActionPerformed

    private void botonRegistroEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRegistroEmpleadoActionPerformed
        RegistroEmpleado r = new RegistroEmpleado();
        r.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonRegistroEmpleadoActionPerformed

    private void botonBorrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarEmpleadoActionPerformed
        BorrarEmpleado emp = new BorrarEmpleado();
        emp.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonBorrarEmpleadoActionPerformed

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        Main atras = new Main();
        atras.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void agregarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarProductoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agregarProductoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministracionDatos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarProducto;
    private javax.swing.JButton botonBorrarEmpleado;
    private javax.swing.JButton botonModificar;
    private javax.swing.JButton botonRegistroEmpleado;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
