/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import ServicioRestaurante.Bebida;
import ServicioRestaurante.Plato;
import ServicioRestaurante.Restaurant;

/**
 *
 * @author Antonio Rodriguez
 */
public class AgregarProducto extends javax.swing.JFrame {

    /**
     * Creates new form AgregarProducto
     */
    public AgregarProducto() {
        initComponents();
        jLabel6.setVisible(false);
        jlabel8.setVisible(false);
        txtOp1.setVisible(false);
        txtOp2.setVisible(false);
        lblAvOp1.setVisible(false);
        lblAvOp2.setVisible(false);
        setSize(901, 499);
        setResizable(false);
        setTitle("Agregar productos");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbTipProd = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtIdP = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        txtOp1 = new javax.swing.JTextField();
        txtOp2 = new javax.swing.JTextField();
        jlabel8 = new javax.swing.JLabel();
        lblAvOp2 = new javax.swing.JLabel();
        lblAvNom = new javax.swing.JLabel();
        lblAvPrec = new javax.swing.JLabel();
        lblAvIdP = new javax.swing.JLabel();
        lblAvOp1 = new javax.swing.JLabel();
        lblTipProd = new javax.swing.JLabel();
        btnAtras = new javax.swing.JButton();
        btnRegistrar1 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        lblTitulo.setFont(new java.awt.Font("Monotype Corsiva", 1, 36)); // NOI18N
        lblTitulo.setText("Registro de Productos");
        getContentPane().add(lblTitulo);
        lblTitulo.setBounds(260, 30, 350, 50);

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel2.setText("Nombre");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(200, 100, 220, 28);

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel3.setText("Id  Productos");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(200, 140, 220, 28);

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel4.setText("Precio");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 180, 220, 30);

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel6.setText("Opcion1");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(200, 260, 220, 30);

        cmbTipProd.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        cmbTipProd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Plato", "Bebida" }));
        cmbTipProd.setSelectedIndex(-1);
        cmbTipProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTipProdActionPerformed(evt);
            }
        });
        getContentPane().add(cmbTipProd);
        cmbTipProd.setBounds(420, 220, 230, 35);

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jLabel7.setText("Tipo de producto");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(200, 220, 230, 30);

        txtNombre.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        txtNombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNombreKeyPressed(evt);
            }
        });
        getContentPane().add(txtNombre);
        txtNombre.setBounds(420, 100, 230, 35);

        txtIdP.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        txtIdP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdPKeyPressed(evt);
            }
        });
        getContentPane().add(txtIdP);
        txtIdP.setBounds(420, 140, 230, 35);

        txtPrecio.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPrecioKeyPressed(evt);
            }
        });
        getContentPane().add(txtPrecio);
        txtPrecio.setBounds(420, 180, 230, 35);

        txtOp1.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        txtOp1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOp1KeyPressed(evt);
            }
        });
        getContentPane().add(txtOp1);
        txtOp1.setBounds(420, 260, 230, 35);

        txtOp2.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        txtOp2.setToolTipText("Ejemplo: Español, Inglés, Mandarín");
        txtOp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOp2ActionPerformed(evt);
            }
        });
        txtOp2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOp2KeyPressed(evt);
            }
        });
        getContentPane().add(txtOp2);
        txtOp2.setBounds(420, 300, 230, 35);

        jlabel8.setFont(new java.awt.Font("Monotype Corsiva", 0, 24)); // NOI18N
        jlabel8.setText("Opcion2");
        getContentPane().add(jlabel8);
        jlabel8.setBounds(200, 300, 120, 30);

        lblAvOp2.setFont(new java.awt.Font("Monotype Corsiva", 1, 28)); // NOI18N
        lblAvOp2.setForeground(new java.awt.Color(204, 0, 0));
        lblAvOp2.setText("*");
        getContentPane().add(lblAvOp2);
        lblAvOp2.setBounds(660, 310, 20, 30);

        lblAvNom.setFont(new java.awt.Font("Monotype Corsiva", 1, 28)); // NOI18N
        lblAvNom.setForeground(new java.awt.Color(204, 0, 0));
        lblAvNom.setText("*");
        getContentPane().add(lblAvNom);
        lblAvNom.setBounds(660, 110, 51, 40);

        lblAvPrec.setFont(new java.awt.Font("Monotype Corsiva", 1, 28)); // NOI18N
        lblAvPrec.setForeground(new java.awt.Color(204, 0, 0));
        lblAvPrec.setText("*");
        getContentPane().add(lblAvPrec);
        lblAvPrec.setBounds(660, 180, 51, 50);

        lblAvIdP.setFont(new java.awt.Font("Monotype Corsiva", 1, 28)); // NOI18N
        lblAvIdP.setForeground(new java.awt.Color(204, 0, 0));
        lblAvIdP.setText("*");
        getContentPane().add(lblAvIdP);
        lblAvIdP.setBounds(660, 140, 51, 40);

        lblAvOp1.setFont(new java.awt.Font("Monotype Corsiva", 1, 28)); // NOI18N
        lblAvOp1.setForeground(new java.awt.Color(204, 0, 0));
        lblAvOp1.setText("*");
        getContentPane().add(lblAvOp1);
        lblAvOp1.setBounds(660, 260, 20, 40);

        lblTipProd.setFont(new java.awt.Font("Monotype Corsiva", 1, 28)); // NOI18N
        lblTipProd.setForeground(new java.awt.Color(204, 0, 0));
        lblTipProd.setText("*");
        getContentPane().add(lblTipProd);
        lblTipProd.setBounds(660, 230, 20, 30);

        btnAtras.setFont(new java.awt.Font("Monotype Corsiva", 0, 28)); // NOI18N
        btnAtras.setText("Atrás");
        btnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtrasActionPerformed(evt);
            }
        });
        getContentPane().add(btnAtras);
        btnAtras.setBounds(10, 10, 100, 40);

        btnRegistrar1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        btnRegistrar1.setText("Registrar");
        btnRegistrar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrar1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegistrar1);
        btnRegistrar1.setBounds(390, 400, 140, 40);

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Desktop\\Sistema de restaurant\\SistemaRestaurant\\src\\Images\\fondo2.jpg")); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 900, 498);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbTipProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTipProdActionPerformed
        if (cmbTipProd.getSelectedIndex()==0){ // plato
            txtOp1.setVisible(true);
            jLabel6.setText("kcals");
            jLabel6.setVisible(true);
            
            jlabel8.setVisible(true);   
            jlabel8.setText("Ingredientes");
            txtOp2.setVisible(true);
            txtOp2.setSize(230, 80);
        }
        else if(cmbTipProd.getSelectedIndex()==1){ // bebida
            txtOp1.setVisible(true);
            jLabel6.setText("Tipo");
            jLabel6.setVisible(true);
            
            jlabel8.setVisible(true);   
            jlabel8.setText("Tamaño");
            txtOp2.setVisible(true);
            txtOp2.setSize(230, 35);
        }
    }//GEN-LAST:event_cmbTipProdActionPerformed

    private void txtNombreKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreKeyPressed
        lblAvNom.setVisible(false);
    }//GEN-LAST:event_txtNombreKeyPressed

    private void txtIdPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdPKeyPressed
        lblAvIdP.setVisible(false);
    }//GEN-LAST:event_txtIdPKeyPressed

    private void txtPrecioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyPressed
        lblAvPrec.setVisible(false);
    }//GEN-LAST:event_txtPrecioKeyPressed

    private void txtOp1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOp1KeyPressed
        lblAvOp1.setVisible(false);
    }//GEN-LAST:event_txtOp1KeyPressed

    private void txtOp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOp2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtOp2ActionPerformed

    private void txtOp2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOp2KeyPressed
        lblAvOp2.setVisible(false);
    }//GEN-LAST:event_txtOp2KeyPressed

    private void btnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtrasActionPerformed
        AdministracionDatos atras = new AdministracionDatos();
        atras.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnAtrasActionPerformed

    private void btnRegistrar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrar1ActionPerformed
        Restaurant rest = Restaurant.getInstance();
        if (txtNombre.getText().isEmpty() | txtIdP.getText().isEmpty() | txtPrecio.getText().isEmpty() | cmbTipProd.getSelectedIndex()==-1){ // so algo esta vacio
            if (txtNombre.getText().isEmpty())
                lblAvNom.setVisible(true);
            if (txtIdP.getText().isEmpty())
                lblAvIdP.setVisible(true);
            if (txtPrecio.getText().isEmpty())
                lblAvPrec.setVisible(true);
            if (txtOp1.getText().isEmpty())
                lblAvOp1.setVisible(true);            
            if (cmbTipProd.getSelectedIndex()==-1)
                lblTipProd.setVisible(true);
        }
        if (cmbTipProd.getSelectedIndex()==0){
            if (txtOp1.getText().isEmpty()){
                lblAvOp1.setVisible(true);
            }
            if (txtOp2.getText().isEmpty()){
                lblAvOp2.setVisible(true);
            }
        }
        else if (cmbTipProd.getSelectedIndex()==1){
            if (txtOp2.getText().isEmpty()){
                lblAvOp2.setVisible(true);
            }
            if (txtOp2.getText().isEmpty()){
                lblAvOp2.setVisible(true);
            }
        }
        if (!txtNombre.getText().isEmpty() & !txtIdP.getText().isEmpty() & !txtPrecio.getText().isEmpty() & !txtOp1.getText().isEmpty() & cmbTipProd.getSelectedIndex()!=-1){ // so algo esta vacio
            
            if (cmbTipProd.getSelectedIndex()==0){
                String idPlato = txtIdP.getText();
                int precio = Integer.parseInt(txtPrecio.getText());
                int kcal = Integer.parseInt(txtOp1.getText());
                Plato plato = new Plato(idPlato, precio,txtNombre.getText(), kcal, txtOp2.getText());
                Restaurant.getInstance().getMenu().agregarProducto(plato);
                Main main = new Main();
                main.setVisible(true);
                this.dispose();
            }
            else if (cmbTipProd.getSelectedIndex()==1){ 
                String idBebida = txtIdP.getText();
                int precio = Integer.parseInt(txtPrecio.getText());
                int tamano = Integer.parseInt(txtOp2.getText());
                Bebida bebida = new Bebida(idBebida, precio,txtNombre.getText(), txtOp1.getText(), tamano);
                Restaurant.getInstance().getMenu().agregarProducto(bebida);
                Main main = new Main();
                main.setVisible(true);
                this.dispose();
            }
            
        }
    }//GEN-LAST:event_btnRegistrar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnRegistrar1;
    private javax.swing.JComboBox<String> cmbTipProd;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jlabel8;
    private javax.swing.JLabel lblAvIdP;
    private javax.swing.JLabel lblAvNom;
    private javax.swing.JLabel lblAvOp1;
    private javax.swing.JLabel lblAvOp2;
    private javax.swing.JLabel lblAvPrec;
    private javax.swing.JLabel lblTipProd;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JTextField txtIdP;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtOp1;
    private javax.swing.JTextField txtOp2;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
