/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Empleados.Cliente;
import Empleados.CrearFabrica;
import ServicioRestaurante.Mesa;
import ServicioRestaurante.Restaurant;
import java.util.ArrayList;
import ServicioRestaurante.Restaurant;
import java.awt.GridLayout;

/**
 *
 * @author Peniche
 */
public class VistaMesas extends javax.swing.JFrame {

    /**
     * Creates new form RegistrarCliente
     */
    public VistaMesas() {
        initComponents();
        
        setTitle("Tomar ordenes");  
        setSize(996, 597);
        setResizable(false);
        setLocationRelativeTo(null);
        //mesasDisponibles();
        
        Restaurant rest = new Restaurant();
        rest.crearMesas();
        
        panelMesas.setLayout(new GridLayout(3, 4,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelMesas = new javax.swing.JPanel();
        numPersonas = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panelMesas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout panelMesasLayout = new javax.swing.GroupLayout(panelMesas);
        panelMesas.setLayout(panelMesasLayout);
        panelMesasLayout.setHorizontalGroup(
            panelMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );
        panelMesasLayout.setVerticalGroup(
            panelMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 496, Short.MAX_VALUE)
        );

        getContentPane().add(panelMesas);
        panelMesas.setBounds(430, 30, 500, 500);

        numPersonas.setFont(new java.awt.Font("Monotype Corsiva", 0, 36)); // NOI18N
        numPersonas.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        numPersonas.setAlignmentX(1.0F);
        numPersonas.setAlignmentY(1.0F);
        numPersonas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        numPersonas.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                numPersonasStateChanged(evt);
            }
        });
        getContentPane().add(numPersonas);
        numPersonas.setBounds(290, 150, 70, 40);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 0, 30)); // NOI18N
        jLabel1.setText("Número de personas");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(50, 150, 240, 35);

        jButton1.setFont(new java.awt.Font("Monotype Corsiva", 0, 30)); // NOI18N
        jButton1.setText("Reservar mesa");
        getContentPane().add(jButton1);
        jButton1.setBounds(110, 230, 190, 40);

        jButton2.setFont(new java.awt.Font("Monotype Corsiva", 0, 28)); // NOI18N
        jButton2.setText("Atrás");
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 20, 100, 30);

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\USUARIO\\Desktop\\Sistema de restaurant\\SistemaRestaurant\\src\\Images\\fondo.jpg")); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(1000, 670));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, -40, 990, 640);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void numPersonasStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_numPersonasStateChanged
        mesasDisponibles();
    }//GEN-LAST:event_numPersonasStateChanged

    public void mesasDisponibles(){
        Restaurant rest = new Restaurant();
        
        ArrayList<Mesa> listaMesas = rest.getMesas();;
        for (int i = 0; i < listaMesas.size(); i++) {
            Mesa mesa = listaMesas.get(i);
            
            mesa.setText(String.valueOf(mesa.getNumMesa()+1));
            if (mesa.getCantPersonas()>=(Integer)numPersonas.getValue()){
                mesa.setEnabled(true);
            }           
            if(mesa.getCantPersonas()<(Integer)numPersonas.getValue()){
                mesa.setEnabled(false);
            }
            if (!mesa.getEstado()){
                mesa.setEnabled(false);
            }
            numPersonas.add(mesa);
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        
        
        
       
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaMesas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner numPersonas;
    private javax.swing.JPanel panelMesas;
    // End of variables declaration//GEN-END:variables
}
